name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to build from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Set this to your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-fs-pages  # The branch the action should deploy to.
        folder: dist     # The folder the action should deploy.
